<?php
$faqs = [
  ['How do you convert square feet to cubic yards?', 'Multiply square feet by depth in feet, then divide by 27. Convert inches to feet before calculating.'],
  ['How many cubic yards cover 1,000 square feet at 3 inches?', 'Three inches is 0.25 feet. 1,000 x 0.25 / 27 = 9.26 cubic yards before overage.'],
  ['Can square feet alone become cubic yards?', 'No. You also need depth or thickness because cubic yards measure volume.'],
  ['What depth should I use for mulch?', 'Use 2 to 3 inches for most mulch projects. Use 4 inches only when the bed needs a heavier layer.'],
  ['What depth should I use for concrete?', 'Many patios and sidewalks use 4 inches. Driveways and heavier slabs may need 5 to 6 inches or more.'],
  ['Does this work for gravel?', 'Yes. Enter the area, planned depth, and gravel material to estimate cubic yards and tons.'],
  ['Should I include overage?', 'Yes, 10 percent extra is a useful planning amount. It helps cover compaction, waste, and uneven ground.'],
  ['How many cubic feet are in a cubic yard?', 'There are 27 cubic feet in 1 cubic yard. The calculator converts that automatically.']
];
$page = ['root' => '../', 'title' => 'Square Feet to Cubic Yards Calculator - Free Converter', 'description' => 'Convert square feet to cubic yards by entering your area and depth. Instant results for concrete, gravel, mulch and more. Free square footage to cubic yards tool.', 'canonical' => 'https://cubicyardcalculator.site/square-feet-to-cubic-yards-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Square Feet to Cubic Yards Calculator', 'url' => 'https://cubicyardcalculator.site/square-feet-to-cubic-yards-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($f) => ['@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f[1]]], $faqs)]]]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Area plus depth converter</p><h1>Square Feet to Cubic Yards Calculator</h1><p class="lead">Enter square feet and depth to calculate cubic yards, cubic feet, cubic meters, weight, tons, and overage for common bulk materials.</p></section>
<section class="tool"><h2>Convert Square Feet to Cubic Yards</h2><form data-calculator="square-feet"><div class="form-grid"><div class="field"><label for="area">Square feet</label><input id="area" name="area" type="number" step="any" required><div class="error" data-error-for="area"></div></div><div class="field"><label for="depth">Depth</label><div class="input-row"><input id="depth" name="depth" type="number" step="any" required><select name="depth_unit"><option value="inches">inches</option><option value="feet">feet</option><option value="yards">yards</option><option value="cm">cm</option><option value="meters">meters</option></select></div><div class="error" data-error-for="depth"></div></div><div class="field full"><label for="material">Material</label><select id="material" name="material"><option value="concrete">Concrete</option><option value="gravel">Gravel</option><option value="dirt">Dirt</option><option value="topsoil">Topsoil</option><option value="mulch">Mulch</option><option value="sand">Sand</option><option value="rock">Rock</option></select></div><div class="button-row"><button class="button-primary" type="submit">Calculate</button><button class="button-secondary" type="reset">Reset</button></div><section class="results"><h2>Results</h2><div class="result-grid"><div class="result-card primary"><span>Cubic Yards</span><strong data-result="yards">0.00</strong></div><div class="result-card"><span>Cubic Feet</span><strong data-result="feet">0.00</strong></div><div class="result-card"><span>Cubic Meters</span><strong data-result="meters">0.00</strong></div><div class="result-card"><span>Weight</span><strong><span data-result="pounds">0</span> lbs</strong><p class="result-note"><span data-result="tons">0.00</span> tons</p></div><div class="result-card"><span>With 10% Overage</span><strong><span data-result="overage">0.00</span> yards</strong></div></div></section></div></form></section>
<section class="content-section"><h2>How to Convert Sq Ft to Cubic Yards</h2><p>Square feet measures area. Cubic yards measures volume, so depth is required. Convert depth to feet, multiply by the area, then divide by 27.</p></section>
<section class="content-section"><h2>Formula Explanation</h2><p>The formula is square feet x depth in feet / 27 = cubic yards. A 600 square foot area at 2 inches deep is 600 x 0.167 / 27 = 3.70 cubic yards.</p></section>
<section class="content-section"><h2>Common Project Examples</h2><div class="table-wrap"><table><tr><th>Area and depth</th><th>Cubic yards</th></tr><tr><td>100 sq ft at 4 in</td><td>1.23</td></tr><tr><td>500 sq ft at 3 in</td><td>4.63</td></tr><tr><td>1,000 sq ft at 2 in</td><td>6.17</td></tr></table></div></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0]) ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1]) ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../concrete-calculator/">Concrete calculator</a><a href="../mulch-calculator/">Mulch calculator</a><a href="../gravel-calculator/">Gravel calculator</a><a href="../">Cubic yard calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
