<?php
$faqs = [
  ['How do I calculate concrete cubic yards?', 'Multiply slab length by width by thickness in feet, then divide by 27. Use the 4 inch, 6 inch, and 8 inch buttons for common slab depths.'],
  ['How many 80 lb bags make a cubic yard?', 'A cubic yard takes about 45 bags of 80 lb concrete mix. Always round up because partial bags are not practical.'],
  ['How many 60 lb bags make a cubic yard?', 'A cubic yard takes about 60 bags of 60 lb concrete mix. For larger work, ready mix delivery is usually easier.'],
  ['How thick should a concrete slab be?', 'Many patios, sidewalks, and light slabs are 4 inches thick. Driveways and heavier slabs often use 5 to 6 inches or more.'],
  ['How much does concrete weigh?', 'Concrete weighs about 4,050 lbs per cubic yard. That is about 2.03 tons per cubic yard.'],
  ['Should I order extra concrete?', 'Yes, 10 percent extra is a practical starting point. Extra concrete covers uneven subgrade, waste, and small measurement errors.'],
  ['How many cubic yards are in a concrete truck?', 'Many ready mix trucks carry around 8 to 10 cubic yards. Minimum order and short load fees vary by supplier.'],
  ['Can I calculate footings with this tool?', 'Yes, enter footing length, width, and depth. For multiple footings, calculate each shape and add the totals.'],
  ['Is a 10x10 slab at 4 inches one cubic yard?', 'It is slightly more than 1 cubic yard. A 10x10 slab at 4 inches needs about 1.23 cubic yards before overage.'],
  ['Does this include rebar or forms?', 'No. The calculator estimates concrete volume, weight, bags, and cost only. Confirm structural details with your contractor or engineer.'],
  ['How many 40 lb bags of concrete are in a cubic yard?', 'About 90 bags of 40 lb concrete mix make one cubic yard. A 40 lb bag yields roughly 0.30 cubic feet, and 27 / 0.30 = 90 bags.'],
  ['How much concrete do I need for a 24x24 slab?', 'A 24x24 ft slab at 4 inches thick needs about 7.11 cubic yards before overage. At 6 inches thick it needs about 10.67 yards. Add 10 percent extra in both cases.'],
  ['How much does a cubic yard of concrete cost in 2026?', 'Ready-mix concrete typically runs $125 to $195 per cubic yard delivered in 2026, varying by region, mix strength, and fuel surcharges. Short-load fees of $50 to $200 often apply to orders under about 4 yards.'],
  ['Should I use bags or ready-mix concrete?', 'Bags work for small pours under about 1 to 2 cubic yards, like fence posts or small pads. Ready-mix delivery is usually cheaper and much faster for larger slabs, driveways, and footings.'],
  ['What is a short load fee for concrete?', 'A short-load fee ($50 to $200) is charged when you order less than a full truck, often under 4 yards. It covers the plant cost of running a partial truck, so small deliveries can cost more per yard.'],
  ['How thick should a concrete driveway be?', 'Residential driveways usually use 4 to 5 inches of concrete, while heavy vehicles and RV pads need 6 inches or more. The subgrade and reinforcement matter as much as thickness.']
];
$page = ['root' => '../', 'title' => 'Concrete Calculator - Cubic Yards for Slabs and Driveways', 'description' => 'Calculate cubic yards of concrete for slabs, driveways and footings. Get volume, 60/80 lb bag counts, weight and cost. Free concrete calculator.', 'canonical' => 'https://cubicyardcalculator.site/concrete-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Concrete Cubic Yard Calculator', 'url' => 'https://cubicyardcalculator.site/concrete-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($f) => ['@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['Concrete Calculator', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Slabs, driveways, patios, and footings</p><h1>Concrete Cubic Yard Calculator</h1><p class="lead">Calculate concrete volume, weight, 60 lb bags, 80 lb bags, cost, and a 10 percent overage recommendation.</p></section>
<section class="tool"><h2>Calculate Concrete</h2><form data-calculator="standard" data-material="concrete"><div class="form-grid"><div class="field"><label for="length">Length</label><div class="input-row"><input id="length" name="length" type="number" step="any" required><select name="length_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="length"></div></div><div class="field"><label for="width">Width</label><div class="input-row"><input id="width" name="width" type="number" step="any" required><select name="width_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="width"></div></div><div class="field"><label for="depth">Thickness</label><div class="input-row"><input id="depth" name="depth" type="number" step="any" required><select name="depth_unit"><option value="inches">inches</option><option value="feet">feet</option><option value="yards">yards</option><option value="cm">cm</option></select></div><div class="preset-row"><button class="preset-button" type="button" data-depth-preset="4">4 inch</button><button class="preset-button" type="button" data-depth-preset="6">6 inch</button><button class="preset-button" type="button" data-depth-preset="8">8 inch</button></div><div class="error" data-error-for="depth"></div></div><div class="field"><label>Material</label><input value="Concrete" disabled></div><div class="field full"><label for="price">Price per cubic yard optional</label><input id="price" name="price" type="number" step="any"><div class="error" data-error-for="price"></div></div><div class="button-row"><button class="button-primary" type="submit">Calculate</button><button class="button-secondary" type="reset">Reset</button></div><section class="results"><h2>Your Concrete Results</h2><div class="result-grid"><div class="result-card primary"><span>Cubic Yards</span><strong data-result="yards">0.00</strong></div><div class="result-card"><span>80 lb Bags</span><strong data-result="bags80">0</strong></div><div class="result-card"><span>60 lb Bags</span><strong data-result="bags60">0</strong></div><div class="result-card"><span>Weight</span><strong><span data-result="pounds">0</span> lbs</strong><p class="result-note"><span data-result="tons">0.00</span> tons</p></div><div class="result-card"><span>Cost</span><strong data-result="cost">$0.00</strong></div><div class="result-card"><span>With 10% Overage</span><strong><span data-result="overage">0.00</span> yards</strong></div></div><p hidden data-result="copy"></p><button class="button-secondary" type="button" data-copy-result>Copy to Clipboard</button></section></div></form></section>
<section class="content-section"><h2>How to Calculate Cubic Yards of Concrete</h2><ol class="steps"><li>Measure the slab or footing length in feet.</li><li>Measure width in feet and thickness in inches.</li><li>Convert thickness to feet, multiply all three dimensions, then divide by 27.</li></ol></section>
<section class="content-section"><h2>Common Concrete Project Reference Table</h2><div class="table-wrap"><table><thead><tr><th>Project</th><th>Size</th><th>4 in thick</th><th>6 in thick</th></tr></thead><tbody><tr><td>Slab / patio</td><td>10x10</td><td>1.23</td><td>1.85</td></tr><tr><td>Driveway</td><td>10x20</td><td>2.47</td><td>3.70</td></tr><tr><td>Two-car driveway</td><td>20x20</td><td>4.94</td><td>7.41</td></tr><tr><td>Garage floor</td><td>24x24</td><td>7.11</td><td>10.67</td></tr><tr><td>Sidewalk</td><td>4x50</td><td>2.47</td><td>-</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Concrete Bag Calculator Table</h2><div class="table-wrap"><table><thead><tr><th>Bag size</th><th>Bags per cubic yard</th><th>Yield per bag</th><th>Best for</th></tr></thead><tbody><tr><td>40 lb</td><td>90</td><td>0.30 cu ft</td><td>Fence posts, tiny repairs</td></tr><tr><td>50 lb</td><td>72</td><td>0.375 cu ft</td><td>Small pads and repairs</td></tr><tr><td>60 lb</td><td>60</td><td>0.45 cu ft</td><td>Small slabs and posts</td></tr><tr><td>80 lb</td><td>45</td><td>0.60 cu ft</td><td>Small slabs and footings</td></tr><tr><td>90 lb</td><td>40</td><td>0.675 cu ft</td><td>Larger small pours</td></tr></tbody></table></div><p>Bag yields come from manufacturer data - an 80 lb bag yields about 0.60 cubic feet. Exact yields vary by mix, so check the bag label and always round up. For full slabs, compare bag cost and labor against ready mix delivery.</p></section>
<section class="content-section"><h2>Worked Example: Standard Driveway</h2><p>A 10 ft by 20 ft driveway at 4 inches thick uses 10 x 20 x 0.333 / 27 = 2.47 cubic yards. With 10 percent overage, order about 2.72 cubic yards before applying supplier minimums.</p></section>
<div class="answer-box">
  <p><strong class="lead-answer">Quick answer:</strong> Multiply length x width x thickness in feet and divide by 27. A 10 x 10 ft slab at 4 inches thick needs (10 x 10 x 0.333) / 27 = <strong>1.23 cubic yards</strong>, or about 55 bags of 80 lb mix with 10 percent overage. For pours over 1 to 2 yards, ready-mix delivery is usually cheaper than bags.</p>
</div>

<section class="content-section" id="concrete-cost">
  <h2>Concrete Cost Per Yard in 2026</h2>
  <p>Ready-mix concrete typically costs <strong>$125 to $195 per cubic yard</strong> delivered in 2026, depending on region, mix strength, and fuel surcharges. Small loads under about 4 yards often add a <strong>short-load fee of $50 to $200</strong>, which is why bags can be cheaper for tiny pours. Always compare the delivered total, not just the per-yard rate, and confirm current pricing with your local plant.</p>
</section>

<section class="content-section" id="concrete-mistakes">
  <h2>Common Concrete Estimating Mistakes</h2>
  <p><strong>Skipping the overage.</strong> Forms leak, subgrade is never perfectly level, and wheelbarrows spill. Ten percent extra is the industry standard.</p>
  <p><strong>Mixing inches and feet.</strong> Convert thickness to feet first (4 in = 0.333 ft). Entering 4 instead of 0.333 inflates the estimate twelvefold.</p>
  <p><strong>Ordering bags for a big pour.</strong> Above roughly 1 to 2 cubic yards, ready-mix is cheaper and far less labor than hauling dozens of bags.</p>
  <p><strong>Ignoring the short-load fee.</strong> Small ready-mix orders can carry fees that make the headline per-yard price misleading.</p>
</section>

<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0]) ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1]) ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../square-feet-to-cubic-yards-calculator/">Square feet to cubic yards calculator</a><a href="../tons-to-cubic-yards-calculator/">Tons to cubic yards calculator</a><a href="../gravel-calculator/">Gravel calculator</a><a href="../">Cubic yard calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
