<?php
$faqs = [
  ['How much does a cubic yard cost?', 'There is no single national price. Cost depends on material, location, supplier, delivery distance, order size, and current local demand.'],
  ['What is usually included in the price?', 'A quote may include only the material, or it may include delivery, loading, taxes, minimum-order fees, and spreading. Ask the supplier what is included.'],
  ['Is buying by the yard cheaper than buying bags?', 'Bulk material is often more economical for larger areas, while bags can be practical for small projects or places without delivery access. Compare the delivered total.'],
  ['How do I estimate my total cost?', 'Multiply the required cubic yards by the supplier price per yard, then add delivery and other listed fees. Include overage in the quantity before calculating the total.']
];
$page = ['root' => '../', 'title' => 'How Much Is a Cubic Yard? Cost and Ordering Guide', 'description' => 'Learn what affects the cost of a cubic yard of dirt, mulch, gravel, sand, rock, or concrete and how to estimate your delivered project total.', 'canonical' => 'https://cubicyardcalculator.site/cubic-yard-cost/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebPage', 'name' => 'How Much Is a Cubic Yard?', 'url' => 'https://cubicyardcalculator.site/cubic-yard-cost/'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['Cubic Yard Cost Guide', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Material cost planning</p><h1>How Much Is a Cubic Yard?</h1><p class="lead">The price of a cubic yard depends on the material, supplier, delivery distance, order size, and local market. Use the guide below to compare quotes accurately.</p></section>
<section class="answer-box"><p><strong class="lead-answer">Important:</strong> A cubic-yard price is not a universal fixed rate. Compare the delivered total and confirm whether the quote includes taxes, delivery, minimums, and fees.</p></section>
<section class="content-section"><h2>What Changes the Price?</h2><div class="table-wrap"><table><thead><tr><th>Factor</th><th>Why it matters</th></tr></thead><tbody><tr><td>Material</td><td>Mulch, soil, gravel, sand, rock, and concrete have different production and handling costs.</td></tr><tr><td>Delivery distance</td><td>Longer routes and difficult access can increase delivery charges.</td></tr><tr><td>Order size</td><td>Suppliers may have minimum charges or different bulk pricing.</td></tr><tr><td>Material grade</td><td>Screening, color, stone size, and blend affect the product price.</td></tr><tr><td>Season and location</td><td>Local demand, weather, and availability can change quotes.</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Estimate Your Material Cost</h2><p>First calculate your required volume, including any overage. Then enter the supplier's price per cubic yard in the calculator to estimate the material cost.</p><p><a class="button button-primary" href="../">Open the Cubic Yard Calculator</a></p></section>
<section class="content-section"><h2>Questions to Ask a Supplier</h2><ul><li>Is the quoted price per cubic yard, ton, bag, or load?</li><li>Is delivery included, and is there a minimum order?</li><li>What material density or product yield should I use?</li><li>Are taxes, loading, fuel, or spreading fees separate?</li><li>How much notice is needed for delivery?</li></ul></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0], ENT_QUOTES, 'UTF-8') ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1], ENT_QUOTES, 'UTF-8') ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Guides</h2><div class="link-grid"><a href="../how-to-calculate-cubic-yards/">How to calculate cubic yards</a><a href="../cubic-yard-coverage/">Cubic yard coverage</a><a href="../tons-to-cubic-yards-calculator/">Tons to cubic yards</a><a href="../concrete-bag-calculator/">Concrete bag calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
