<?php
$faqs = [
  ['What is the formula for cubic feet to cubic yards?', 'Divide the number of cubic feet by 27.'],
  ['How many cubic feet are in one cubic yard?', 'One cubic yard contains 27 cubic feet.'],
  ['Can I convert cubic yards to cubic feet?', 'Yes. Select cubic yards as the input and multiply the amount by 27.']
];
$page = ['root' => '../', 'title' => 'Cubic Feet to Cubic Yards Calculator - Convert Both Ways', 'description' => 'Convert cubic feet to cubic yards or cubic yards to cubic feet with this free two-way volume converter. One cubic yard equals 27 cubic feet.', 'canonical' => 'https://cubicyardcalculator.site/cubic-feet-to-cubic-yards-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Cubic Feet to Cubic Yards Calculator', 'url' => 'https://cubicyardcalculator.site/cubic-feet-to-cubic-yards-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['Cubic Feet to Cubic Yards Calculator', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Two-way volume converter</p><h1>Cubic Feet to Cubic Yards Calculator</h1><p class="lead">Convert cubic feet to cubic yards or cubic yards to cubic feet. The conversion is based on 27 cubic feet per cubic yard.</p></section>
<section class="tool"><h2>Convert Cubic Feet and Cubic Yards</h2><form data-calculator="cubic-conversion"><div class="form-grid"><div class="field full"><span class="legend">Convert from</span><label><input type="radio" name="convert_mode" value="feet" checked> Cubic feet</label><label><input type="radio" name="convert_mode" value="yards"> Cubic yards</label></div><div class="field"><label for="amount">Amount</label><input id="amount" name="amount" type="number" min="0" step="any" required><div class="error" data-error-for="amount"></div></div><div class="button-row"><button class="button-primary" type="submit">Convert</button><button class="button-secondary" type="reset">Reset</button></div><section class="results" aria-live="polite"><h2>Conversion Result</h2><div class="result-grid"><div class="result-card primary"><span>Converted value</span><strong data-result="converted">0.00</strong></div></div><p data-result="explanation"></p></section></div></form></section>
<section class="content-section"><h2>Conversion Formula</h2><p><strong>Cubic feet ÷ 27 = cubic yards.</strong> To reverse the calculation, use <strong>cubic yards × 27 = cubic feet</strong>.</p><div class="table-wrap"><table><thead><tr><th>Cubic feet</th><th>Cubic yards</th></tr></thead><tbody><tr><td>27</td><td>1</td></tr><tr><td>54</td><td>2</td></tr><tr><td>81</td><td>3</td></tr><tr><td>135</td><td>5</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../">Cubic yard calculator</a><a href="../square-feet-to-cubic-yards-calculator/">Square feet to cubic yards</a><a href="../tons-to-cubic-yards-calculator/">Tons to cubic yards</a></div></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0], ENT_QUOTES, 'UTF-8') ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1], ENT_QUOTES, 'UTF-8') ?></p></div></div><?php endforeach; ?></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
