<?php
$faqs = [
  ['What is the formula for cubic yards?', 'Multiply length, width, and depth in feet, then divide the result by 27.'],
  ['How do I convert inches to feet?', 'Divide the number of inches by 12. For example, 4 inches equals 0.333 feet.'],
  ['Should I order extra material?', 'A 10 percent overage is a common planning allowance for waste, compaction, uneven ground, and measuring differences.'],
  ['Does the material change the volume?', 'No. The volume formula is the same, but material density changes the estimated weight.']
];
$page = ['root' => '../', 'title' => 'How to Calculate Cubic Yards - Formula and Examples', 'description' => 'Learn how to calculate cubic yards for concrete, gravel, mulch, dirt and sand. Includes the formula, inch-to-feet conversion and worked examples.', 'canonical' => 'https://cubicyardcalculator.site/how-to-calculate-cubic-yards/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'HowTo', 'name' => 'How to Calculate Cubic Yards', 'step' => [['@type' => 'HowToStep', 'name' => 'Measure length and width', 'text' => 'Measure the project length and width in feet.'], ['@type' => 'HowToStep', 'name' => 'Convert depth to feet', 'text' => 'Divide depth in inches by 12 when needed.'], ['@type' => 'HowToStep', 'name' => 'Apply the formula', 'text' => 'Multiply length by width by depth, then divide by 27.']]], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['How to Calculate Cubic Yards', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Volume estimation guide</p><h1>How to Calculate Cubic Yards</h1><p class="lead">Multiply length × width × depth in feet, then divide by 27. This works for concrete, gravel, mulch, dirt, sand, and other materials sold by volume.</p></section>
<section class="answer-box"><p><strong class="lead-answer">Formula:</strong> length in feet × width in feet × depth in feet ÷ 27 = cubic yards.</p></section>
<section class="content-section"><h2>Three Steps</h2><ol class="steps"><li>Measure the length and width of the project area in feet.</li><li>Measure the material depth. Convert inches to feet by dividing by 12.</li><li>Multiply the three measurements and divide by 27.</li></ol></section>
<section class="content-section"><h2>Worked Examples</h2><div class="table-wrap"><table><thead><tr><th>Project</th><th>Calculation</th><th>Result</th></tr></thead><tbody><tr><td>10 × 10 patio at 4 inches</td><td>10 × 10 × 0.333 ÷ 27</td><td>1.23 cubic yards</td></tr><tr><td>20 × 20 driveway at 4 inches</td><td>20 × 20 × 0.333 ÷ 27</td><td>4.94 cubic yards</td></tr><tr><td>200 sq ft mulch bed at 3 inches</td><td>200 × 0.25 ÷ 27</td><td>1.85 cubic yards</td></tr><tr><td>4 × 8 raised bed at 12 inches</td><td>4 × 8 × 1 ÷ 27</td><td>1.19 cubic yards</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Allow for Overage</h2><p>Multiply the calculated volume by 1.10 for a 10 percent overage. This helps account for compaction, spillage, uneven ground, and small measurement differences.</p><p><a class="button button-primary" href="../">Calculate your project volume</a></p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0], ENT_QUOTES, 'UTF-8') ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1], ENT_QUOTES, 'UTF-8') ?></p></div></div><?php endforeach; ?></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
