<?php
$faqs = [
  ['How much area does one cubic yard cover?', 'One cubic yard covers 324 square feet at 1 inch deep, 162 square feet at 2 inches, 108 square feet at 3 inches, and 81 square feet at 4 inches.'],
  ['How many square feet does a cubic yard cover at 2 inches?', 'One cubic yard covers about 162 square feet at a 2-inch depth.'],
  ['How many square feet does a cubic yard cover at 3 inches?', 'One cubic yard covers about 108 square feet at a 3-inch depth.'],
  ['Does material type change coverage?', 'No. Coverage is based on volume and depth. Material type changes weight, settling, and how much overage you may want.']
];
$page = ['root' => '../', 'title' => 'Cubic Yard Coverage Calculator and Chart by Depth', 'description' => 'Find out how many square feet one cubic yard covers at common depths. Use the coverage chart and calculator for mulch, gravel, soil, sand, and concrete.', 'canonical' => 'https://cubicyardcalculator.site/cubic-yard-coverage/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebPage', 'name' => 'Cubic Yard Coverage Calculator', 'url' => 'https://cubicyardcalculator.site/cubic-yard-coverage/'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['Cubic Yard Coverage', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Volume coverage guide</p><h1>Cubic Yard Coverage Calculator and Chart</h1><p class="lead">Find how many square feet one cubic yard covers at common depths for mulch, gravel, dirt, sand, and concrete.</p></section>
<section class="answer-box"><p><strong class="lead-answer">Quick answer:</strong> One cubic yard covers 108 square feet at 3 inches deep, 81 square feet at 4 inches, and 54 square feet at 6 inches.</p></section>
<section class="content-section"><h2>Cubic Yard Coverage Chart</h2><div class="table-wrap"><table><thead><tr><th>Depth</th><th>Coverage per cubic yard</th><th>Common application</th></tr></thead><tbody><tr><td>1 inch</td><td>324 sq ft</td><td>Thin topdressing</td></tr><tr><td>2 inches</td><td>162 sq ft</td><td>Light mulch or rock refresh</td></tr><tr><td>3 inches</td><td>108 sq ft</td><td>Mulch beds and landscape rock</td></tr><tr><td>4 inches</td><td>81 sq ft</td><td>Concrete slabs and heavier beds</td></tr><tr><td>6 inches</td><td>54 sq ft</td><td>Driveway or shed base</td></tr><tr><td>8 inches</td><td>40.5 sq ft</td><td>Deep base or heavy fill</td></tr><tr><td>12 inches</td><td>27 sq ft</td><td>One-foot fill or raised beds</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Coverage Formula</h2><p>To calculate coverage, convert depth to feet and divide 27 cubic feet by that depth:</p><p class="answer-box"><strong>Coverage in square feet = 27 ÷ depth in feet</strong></p><p>For example, 3 inches is 0.25 feet. Then 27 ÷ 0.25 = 108 square feet per cubic yard.</p></section>
<section class="content-section"><h2>Calculate Your Required Volume</h2><p>Enter your project's length, width, and depth to calculate the total cubic yards needed. Add about 10 percent for settling, waste, or uneven ground.</p><p><a class="button button-primary" href="../">Open the Cubic Yard Calculator</a></p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0], ENT_QUOTES, 'UTF-8') ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1], ENT_QUOTES, 'UTF-8') ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Tools</h2><div class="link-grid"><a href="../square-feet-to-cubic-yards-calculator/">Square feet to cubic yards</a><a href="../mulch-calculator/">Mulch calculator</a><a href="../gravel-calculator/">Gravel calculator</a><a href="../fill-dirt-calculator/">Fill dirt calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
