<?php
$faqs = [
  ['How do you calculate square yards?', 'Multiply the length by the width in feet, then divide the square feet by 9.'],
  ['How many square feet are in a square yard?', 'There are 9 square feet in 1 square yard because a yard is 3 feet long and 3 feet wide.'],
  ['Is a square yard the same as a cubic yard?', 'No. A square yard measures area. A cubic yard measures volume and also requires depth.']
];
$page = ['root' => '../', 'title' => 'Square Yard Calculator - Convert Square Feet to Square Yards', 'description' => 'Calculate square yards from length and width with this free square yard calculator. Convert square feet to square yards for flooring, landscaping, fabric and more.', 'canonical' => 'https://cubicyardcalculator.site/square-yard-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Square Yard Calculator', 'url' => 'https://cubicyardcalculator.site/square-yard-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]], $faqs)]]]];
$page['breadcrumbs'] = [['Home', 'https://cubicyardcalculator.site/'], ['Square Yard Calculator', null]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Area converter</p><h1>Square Yard Calculator</h1><p class="lead">Enter length and width to calculate square feet and square yards. Use this for flooring, landscaping, fabric, turf, and other area measurements.</p></section>
<section class="tool"><h2>Calculate Square Yards</h2><form data-calculator="square-yards"><div class="form-grid"><div class="field"><label for="length">Length</label><div class="input-row"><input id="length" name="length" type="number" min="0" step="any" required><select name="length_unit" aria-label="Length unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option></select></div><div class="error" data-error-for="length"></div></div><div class="field"><label for="width">Width</label><div class="input-row"><input id="width" name="width" type="number" min="0" step="any" required><select name="width_unit" aria-label="Width unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option></select></div><div class="error" data-error-for="width"></div></div><div class="button-row"><button class="button-primary" type="submit">Calculate</button><button class="button-secondary" type="reset">Reset</button></div><section class="results" aria-live="polite"><h2>Your Area Results</h2><div class="result-grid"><div class="result-card primary"><span>Square yards</span><strong data-result="squareYards">0.00</strong></div><div class="result-card"><span>Square feet</span><strong data-result="squareFeet">0.00</strong></div></div><p data-result="explanation"></p></section></div></form></section>
<section class="content-section"><h2>How to Calculate Square Yards</h2><p>First calculate the area in square feet by multiplying length by width. Then divide by 9 because 1 square yard equals 9 square feet.</p><p><strong>Length in feet × width in feet ÷ 9 = square yards</strong></p></section>
<section class="content-section"><h2>Common Conversions</h2><div class="table-wrap"><table><thead><tr><th>Square feet</th><th>Square yards</th></tr></thead><tbody><tr><td>9</td><td>1</td></tr><tr><td>100</td><td>11.11</td></tr><tr><td>500</td><td>55.56</td></tr><tr><td>900</td><td>100</td></tr><tr><td>1,000</td><td>111.11</td></tr></tbody></table></div></section>
<section class="content-section"><h2>Square Yards Versus Cubic Yards</h2><p>Square yards measure a flat area and need only length and width. Cubic yards measure volume and need length, width, and depth. For soil, mulch, gravel, or concrete, use the <a href="../">cubic yard calculator</a> instead.</p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0], ENT_QUOTES, 'UTF-8') ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1], ENT_QUOTES, 'UTF-8') ?></p></div></div><?php endforeach; ?></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
