<?php
$faqs = [
  ['How do you convert tons to cubic yards?', 'Divide tons by the tons per cubic yard for the selected material. Density changes by material, so the same tonnage gives different volumes.'],
  ['How many cubic yards are in a ton of gravel?', 'Using 2,800 lbs per cubic yard, 1 ton of gravel is about 0.71 cubic yards. Local rock type and moisture can change that estimate.'],
  ['How many tons are in a cubic yard of concrete?', 'A cubic yard of concrete weighs about 4,050 lbs, or 2.03 tons. Wet mixes and reinforcement are not included in this simple estimate.'],
  ['Why are tons and cubic yards different?', 'Tons measure weight, while cubic yards measure volume. Heavy materials have more tons per cubic yard than light materials.'],
  ['Do suppliers sell by ton or cubic yard?', 'Aggregates like gravel and sand are often sold by ton. Mulch, soil, and concrete are commonly sold by cubic yard.'],
  ['Can I use one conversion for every material?', 'No. Material density changes the conversion, so always select the closest material type.'],
  ['Is a short ton 2,000 lbs?', 'Yes. This calculator uses the US short ton, which equals 2,000 lbs.'],
  ['Should I round up my order?', 'Yes, most bulk material orders should be rounded up. Rounding helps cover compaction, waste, and delivery minimums.']
];
$page = ['root' => '../', 'title' => 'Tons to Cubic Yards Calculator - Convert Any Material', 'description' => 'Convert tons to cubic yards or cubic yards to tons instantly. Supports concrete, gravel, dirt, sand and more. Free two-way conversion calculator.', 'canonical' => 'https://cubicyardcalculator.site/tons-to-cubic-yards-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Tons to Cubic Yards Calculator', 'url' => 'https://cubicyardcalculator.site/tons-to-cubic-yards-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($f) => ['@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f[1]]], $faqs)]]]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Two-way bulk material converter</p><h1>Tons to Cubic Yards Calculator</h1><p class="lead">Convert tons to cubic yards, or cubic yards to tons, using common material densities for concrete, gravel, dirt, mulch, sand, and rock.</p></section>
<section class="tool"><h2>Convert Tons and Cubic Yards</h2><form data-calculator="tons"><div class="form-grid"><div class="field full"><span class="legend">Convert from</span><label><input type="radio" name="convert_mode" value="tons" checked> Tons</label><label><input type="radio" name="convert_mode" value="yards"> Cubic yards</label></div><div class="field"><label for="amount">Amount</label><input id="amount" name="amount" type="number" step="any" required><div class="error" data-error-for="amount"></div></div><div class="field"><label for="material">Material</label><select id="material" name="material"><option value="concrete">Concrete</option><option value="gravel">Gravel</option><option value="dirt">Dirt</option><option value="topsoil">Topsoil</option><option value="mulch">Mulch</option><option value="sand">Sand</option><option value="rock">Rock</option></select></div><div class="button-row"><button class="button-primary" type="submit">Convert</button><button class="button-secondary" type="reset">Reset</button></div><section class="results"><h2>Results</h2><div class="result-grid"><div class="result-card primary"><span>Converted Value</span><strong data-result="converted">0.00</strong></div><div class="result-card"><span>Weight Confirmation</span><strong data-result="confirmation">0.00</strong></div></div></section></div></form></section>
<section class="content-section"><h2>Why Tons and Cubic Yards Differ by Material</h2><p>A ton is a weight measurement, while a cubic yard is a volume measurement. One cubic yard of mulch is light, one cubic yard of concrete is heavy, and gravel or sand usually sits between those examples. That is why a material selector is required for a useful conversion.</p></section>
<section class="content-section"><h2>Conversion Table by Material</h2><div class="table-wrap"><table><tr><th>Material</th><th>Lbs per cubic yard</th><th>Tons per cubic yard</th></tr><tr><td>Concrete</td><td>4,050</td><td>2.03</td></tr><tr><td>Gravel</td><td>2,800</td><td>1.40</td></tr><tr><td>Dirt</td><td>2,200</td><td>1.10</td></tr><tr><td>Topsoil</td><td>2,400</td><td>1.20</td></tr><tr><td>Mulch</td><td>800</td><td>0.40</td></tr><tr><td>Sand</td><td>2,700</td><td>1.35</td></tr><tr><td>Rock</td><td>4,500</td><td>2.25</td></tr></table></div></section>
<section class="content-section"><h2>How Suppliers Sell Bulk Materials</h2><p>Stone yards often quote gravel, rock, and sand by the ton because truck scales make weight easy to verify. Landscape suppliers often quote mulch and soil by the cubic yard because these products are loaded by bucket volume. Concrete is ordered by cubic yard because the project form volume determines the order.</p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0]) ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1]) ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../gravel-calculator/">Gravel calculator</a><a href="../sand-calculator/">Sand calculator</a><a href="../concrete-calculator/">Concrete calculator</a><a href="../">Cubic yard calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
