<?php
$faqs = [
  ['How do I calculate concrete cubic yards?', 'Multiply slab length by width by thickness in feet, then divide by 27. Use the 4 inch, 6 inch, and 8 inch buttons for common slab depths.'],
  ['How many 80 lb bags make a cubic yard?', 'A cubic yard takes about 34 bags of 80 lb concrete mix. Always round up because partial bags are not practical.'],
  ['How many 60 lb bags make a cubic yard?', 'A cubic yard takes about 45 bags of 60 lb concrete mix. For larger work, ready mix delivery is usually easier.'],
  ['How thick should a concrete slab be?', 'Many patios, sidewalks, and light slabs are 4 inches thick. Driveways and heavier slabs often use 5 to 6 inches or more.'],
  ['How much does concrete weigh?', 'Concrete weighs about 4,050 lbs per cubic yard. That is about 2.03 tons per cubic yard.'],
  ['Should I order extra concrete?', 'Yes, 10 percent extra is a practical starting point. Extra concrete covers uneven subgrade, waste, and small measurement errors.'],
  ['How many cubic yards are in a concrete truck?', 'Many ready mix trucks carry around 8 to 10 cubic yards. Minimum order and short load fees vary by supplier.'],
  ['Can I calculate footings with this tool?', 'Yes, enter footing length, width, and depth. For multiple footings, calculate each shape and add the totals.'],
  ['Is a 10x10 slab at 4 inches one cubic yard?', 'It is slightly more than 1 cubic yard. A 10x10 slab at 4 inches needs about 1.23 cubic yards before overage.'],
  ['Does this include rebar or forms?', 'No. The calculator estimates concrete volume, weight, bags, and cost only. Confirm structural details with your contractor or engineer.']
];
$page = ['root' => '../', 'title' => 'Concrete Cubic Yard Calculator - Slabs, Driveways and Footings', 'description' => 'Calculate cubic yards of concrete for any project. Enter dimensions to get cubic yards, bags needed and weight. Free concrete calculator for slabs, driveways and footings.', 'canonical' => 'https://cubicyardcalculator.site/concrete-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Concrete Cubic Yard Calculator', 'url' => 'https://cubicyardcalculator.site/concrete-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($f) => ['@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f[1]]], $faqs)]]]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Slabs, driveways, patios, and footings</p><h1>Concrete Cubic Yard Calculator</h1><p class="lead">Calculate concrete volume, weight, 60 lb bags, 80 lb bags, cost, and a 10 percent overage recommendation.</p></section>
<section class="tool"><h2>Calculate Concrete</h2><form data-calculator="standard" data-material="concrete"><div class="form-grid"><div class="field"><label for="length">Length</label><div class="input-row"><input id="length" name="length" type="number" step="any" required><select name="length_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="length"></div></div><div class="field"><label for="width">Width</label><div class="input-row"><input id="width" name="width" type="number" step="any" required><select name="width_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="width"></div></div><div class="field"><label for="depth">Thickness</label><div class="input-row"><input id="depth" name="depth" type="number" step="any" required><select name="depth_unit"><option value="inches">inches</option><option value="feet">feet</option><option value="yards">yards</option><option value="cm">cm</option></select></div><div class="preset-row"><button class="preset-button" type="button" data-depth-preset="4">4 inch</button><button class="preset-button" type="button" data-depth-preset="6">6 inch</button><button class="preset-button" type="button" data-depth-preset="8">8 inch</button></div><div class="error" data-error-for="depth"></div></div><div class="field"><label>Material</label><input value="Concrete" disabled></div><div class="field full"><label for="price">Price per cubic yard optional</label><input id="price" name="price" type="number" step="any"><div class="error" data-error-for="price"></div></div><div class="button-row"><button class="button-primary" type="submit">Calculate</button><button class="button-secondary" type="reset">Reset</button></div><section class="results"><h2>Results</h2><div class="result-grid"><div class="result-card primary"><span>Cubic Yards</span><strong data-result="yards">0.00</strong></div><div class="result-card"><span>80 lb Bags</span><strong data-result="bags80">0</strong></div><div class="result-card"><span>60 lb Bags</span><strong data-result="bags60">0</strong></div><div class="result-card"><span>Weight</span><strong><span data-result="pounds">0</span> lbs</strong><p class="result-note"><span data-result="tons">0.00</span> tons</p></div><div class="result-card"><span>Cost</span><strong data-result="cost">$0.00</strong></div><div class="result-card"><span>With 10% Overage</span><strong><span data-result="overage">0.00</span> yards</strong></div></div><p hidden data-result="copy"></p><button class="button-secondary" type="button" data-copy-result>Copy to Clipboard</button></section></div></form></section>
<section class="content-section"><h2>How to Calculate Cubic Yards of Concrete</h2><ol class="steps"><li>Measure the slab or footing length in feet.</li><li>Measure width in feet and thickness in inches.</li><li>Convert thickness to feet, multiply all three dimensions, then divide by 27.</li></ol></section>
<section class="content-section"><h2>Common Concrete Project Reference Table</h2><div class="table-wrap"><table><tr><th>Project</th><th>Size</th><th>Cubic yards</th></tr><tr><td>Slab</td><td>10x10 at 4 in</td><td>1.23</td></tr><tr><td>Driveway</td><td>10x20 at 4 in</td><td>2.47</td></tr><tr><td>Patio</td><td>10x10 at 4 in</td><td>1.23</td></tr><tr><td>Garage floor</td><td>20x20 at 4 in</td><td>4.94</td></tr><tr><td>Sidewalk</td><td>12x12 at 4 in</td><td>1.78</td></tr></table></div></section>
<section class="content-section"><h2>Concrete Bag Calculator Table</h2><div class="table-wrap"><table><tr><th>Bag size</th><th>Bags per cubic yard</th><th>Best for</th></tr><tr><td>60 lb</td><td>45</td><td>Small pads and repairs</td></tr><tr><td>80 lb</td><td>34</td><td>Small slabs and posts</td></tr></table></div><p>For full slabs, compare bag cost and labor against ready mix delivery. Bagged concrete is convenient, but mixing dozens of bags is slow.</p></section>
<section class="content-section"><h2>Worked Example: Standard Driveway</h2><p>A 10 ft by 20 ft driveway at 4 inches thick uses 10 x 20 x 0.333 / 27 = 2.47 cubic yards. With 10 percent overage, order about 2.72 cubic yards before applying supplier minimums.</p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0]) ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1]) ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../square-feet-to-cubic-yards-calculator/">Square feet to cubic yards calculator</a><a href="../tons-to-cubic-yards-calculator/">Tons to cubic yards calculator</a><a href="../gravel-calculator/">Gravel calculator</a><a href="../">Cubic yard calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
