<?php
$faqs = [
  ['How do I calculate cubic yards of sand?', 'Multiply length by width by depth in feet, then divide by 27. Use inches for shallow paver or pool base depths.'],
  ['How much does a cubic yard of sand weigh?', 'Sand is about 2,700 lbs per cubic yard. Wet sand can weigh more, so confirm hauling limits.'],
  ['How many tons are in a cubic yard of sand?', 'Using 2,700 lbs per cubic yard, sand is about 1.35 tons per cubic yard.'],
  ['How deep should paver sand be?', 'A 1 inch bedding layer is common for pavers after the base is prepared. Follow the paver manufacturer or contractor guidance.'],
  ['Can this calculator be used for play sand?', 'Yes. It estimates volume and weight, but bagged play sand packaging may use cubic feet or pounds.'],
  ['Should I order extra sand?', 'Yes, about 10 percent extra helps cover leveling, compaction, and waste.'],
  ['Is mason sand the same as fill sand?', 'No. Mason sand is finer and cleaner, while fill sand is used for general filling and grading.'],
  ['How do I convert sand tons to yards?', 'Use the tons to cubic yards calculator and choose sand. The conversion depends on sand density and moisture.']
];
$page = ['root' => '../', 'title' => 'Sand Cubic Yard Calculator - Free Sand Volume Tool', 'description' => 'Calculate cubic yards of sand for pavers, pools, leveling and fill. Get cubic yards, tons, weight and overage with this free sand calculator.', 'canonical' => 'https://cubicyardcalculator.site/sand-calculator/', 'schema' => ['@context' => 'https://schema.org', '@graph' => [['@type' => 'WebApplication', 'name' => 'Sand Cubic Yard Calculator', 'url' => 'https://cubicyardcalculator.site/sand-calculator/', 'applicationCategory' => 'CalculatorApplication', 'operatingSystem' => 'Any'], ['@type' => 'FAQPage', 'mainEntity' => array_map(fn($f) => ['@type' => 'Question', 'name' => $f[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f[1]]], $faqs)]]]];
include __DIR__ . '/../includes/header.php';
?>
<section class="hero"><p class="eyebrow">Pavers, pools, leveling, and fill</p><h1>Sand Cubic Yard Calculator</h1><p class="lead">Calculate sand volume in cubic yards, cubic feet, cubic meters, pounds, tons, cost, and recommended overage.</p></section>
<section class="tool"><h2>Calculate Sand</h2><form data-calculator="standard" data-material="sand"><div class="form-grid"><div class="field"><label for="length">Length</label><div class="input-row"><input id="length" name="length" type="number" step="any" required><select name="length_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="length"></div></div><div class="field"><label for="width">Width</label><div class="input-row"><input id="width" name="width" type="number" step="any" required><select name="width_unit"><option value="feet">feet</option><option value="yards">yards</option><option value="meters">meters</option><option value="inches">inches</option><option value="cm">cm</option></select></div><div class="error" data-error-for="width"></div></div><div class="field"><label for="depth">Depth</label><div class="input-row"><input id="depth" name="depth" type="number" step="any" required><select name="depth_unit"><option value="inches">inches</option><option value="feet">feet</option><option value="yards">yards</option><option value="cm">cm</option></select></div><div class="preset-row"><button class="preset-button" type="button" data-depth-preset="1">1 in bedding</button><button class="preset-button" type="button" data-depth-preset="2">2 in leveling</button><button class="preset-button" type="button" data-depth-preset="4">4 in base</button></div><div class="error" data-error-for="depth"></div></div><div class="field"><label>Material</label><input value="Sand" disabled></div><div class="field full"><label for="price">Price per cubic yard optional</label><input id="price" name="price" type="number" step="any"><div class="error" data-error-for="price"></div></div><div class="button-row"><button class="button-primary" type="submit">Calculate</button><button class="button-secondary" type="reset">Reset</button></div><section class="results"><h2>Results</h2><div class="result-grid"><div class="result-card primary"><span>Cubic Yards</span><strong data-result="yards">0.00</strong></div><div class="result-card"><span>Tons</span><strong data-result="tons">0.00</strong></div><div class="result-card"><span>Weight</span><strong><span data-result="pounds">0</span> lbs</strong></div><div class="result-card"><span>Cubic Feet</span><strong data-result="feet">0.00</strong></div><div class="result-card"><span>Cost</span><strong data-result="cost">$0.00</strong></div><div class="result-card"><span>With 10% Overage</span><strong><span data-result="overage">0.00</span> yards</strong></div></div><p hidden data-result="copy"></p><button class="button-secondary" type="button" data-copy-result>Copy to Clipboard</button></section></div></form></section>
<section class="content-section"><h2>Common Sand Uses</h2><p>Sand is used for paver bedding, pool bases, leveling, trench fill, play areas, and masonry work. The right depth depends on the base and the type of sand being placed.</p></section>
<section class="content-section"><h2>Sand Depth Guide</h2><div class="table-wrap"><table><tr><th>Project</th><th>Typical depth</th></tr><tr><td>Paver bedding</td><td>1 inch</td></tr><tr><td>Leveling layer</td><td>2 inches</td></tr><tr><td>Base or fill layer</td><td>4 inches or more</td></tr></table></div></section>
<section class="content-section"><h2>Sand Weight and Ordering</h2><p>Sand is commonly priced by ton or cubic yard depending on supplier. Because moisture changes weight, use the calculator for planning and confirm final order quantities with the yard before delivery.</p></section>
<section class="content-section"><h2>FAQ</h2><?php foreach ($faqs as $faq): ?><div class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false"><?= htmlspecialchars($faq[0]) ?><span>+</span></button></h3><div class="faq-answer"><p><?= htmlspecialchars($faq[1]) ?></p></div></div><?php endforeach; ?></section>
<section class="content-section"><h2>Related Calculators</h2><div class="link-grid"><a href="../gravel-calculator/">Gravel calculator</a><a href="../tons-to-cubic-yards-calculator/">Tons to cubic yards calculator</a><a href="../square-feet-to-cubic-yards-calculator/">Square feet to cubic yards calculator</a><a href="../">Cubic yard calculator</a></div></section>
<?php include __DIR__ . '/../includes/footer.php'; ?>
